<?php
set_time_limit(0);
$cstart = microtime(true);
header('Content-Type: application/json');
require 'config.php';

$users = array();
$remove = array();
$message = array();
$chats = array();
$rcount = 0;
$acount = 0;
$code = 0;
$backup = false;
$bot_id = bot('getMe')->result->id;

$cron = getSettings('cron');
if($cron < '1' || ($cron - getUsers()) >= PER_MIN) {
    $cron = 0;
}
$nextcron = ($cron + PER_MIN);

$gall = json_decode(file_get_contents('sendtoall.json'), true);
if($gall['list'] == []) {
    $message = array('sent' => 0, 'completed' => false);
}
else {
    foreach($gall['list'] as $id => $val) {
        $send_part = PER_MIN;
        $members = [];
        $query = mysqli_query($db, "SELECT * FROM `".$val['user_table']."`");
        $members_count = mysqli_num_rows($query);
        for($i = 0; $i < $members_count; $i++) { 
        	$u = mysqli_fetch_assoc($query);
            $members[] = $u[$val['chatid_structure']];
        }
        $to_send = array_splice($members, $val['send'], $send_part);
        $val['send'] = ($val['send'] + $send_part);
        foreach($to_send as $u) {
            bot($val['type'], json_decode(str_replace('[*USER*]', $u, $val['data']), true));
        }
        if($val['send'] >= $members_count) {
            unset($gall['list'][$id]);
            file_put_contents('sendtoall.json', json_encode($gall));
            $message = array('sent' => $send_part, 'completed' => true);
        }
        else {
            $gall['list'][$id] = $val;
            file_put_contents('sendtoall.json', json_encode($gall));
            $message = array('sent' => $send_part, 'completed' => false);
        }
    }
}

$res = mysqli_query($db, "SELECT * FROM `users` WHERE `step` LIKE '%sarch_%'");
$rows = mysqli_num_rows($res);
if($rows > 0) {
    while($row = mysqli_fetch_assoc($res)) {
        $user_id = $row['id'];
        $step = $row['step'];
        $value = str_replace('sarch_', '', $step);
        sendFiles($user_id, $value);
    }
}

$res = mysqli_query($db, "SELECT * FROM `users` WHERE `step` LIKE '%wnud_%'");
$rows = mysqli_num_rows($res);
if($rows > 0) {
    $max_request = 15;
    while($row = mysqli_fetch_assoc($res)) {
        $user_id = $row['id'];
        $step = $row['step'];
        $data = str_replace('wnud_', '', $step);
        $id = explode(':', $data)[0];
        $try = explode(':', $data)[1];
        $link1 = "https://mmdcatty.cloud/images/$id/$id"."1.jpg";
        $link2 = "https://mmdcatty.cloud/images/$id/$id"."2.jpg";
        $next_try = ($try + 1);
        if($try < $max_request) {
            if(getimagesize($link1)) {
                $key = retIKey26($link1, $link2);
                setUser($user_id, 'step', '-1');
                sendMessage($user_id, "<b>*</b> Requested image has generated by AI 🤖\n<b>-</b> Use the buttons below to download them\n\n[ ~<b>$next_try"."min</b> took to generate ]", -1, $key);
            }
            else {
                setUser($user_id, 'step', "wnud_$id:$next_try");
                sendMessage($user_id, "Still working on your request...\n<b>Tries: $next_try/$max_request</b>");
            }
        }
        else {
            $price = getSettings('nude_price');
            $balance = getUser($user_id, 'balance');
            setUser($user_id, 'balance', ($balance + $price));
            setUser($user_id, 'step', '-1');
            sendMessage($user_id, "Something went wrong.\n<b>$price Stock Coins</b> has refunded");
        }
    }
}

$res = mysqli_query($db, "SELECT * FROM `hosts` WHERE `expire` < '".time()."' AND `status` = '1'");
$rows = mysqli_num_rows($res);
if($rows > 0) {
    while($row = mysqli_fetch_assoc($res)) {
        $host_id = $row['id'];
        $user_id = $row['user_id'];
        $host_username = $row['username'];
        suspendHost($host_username);
        setHost($host_id, 'status', '0');
        sendMessage($user_id, "Your host (<code>$host_username</code>) has expired and got suspended", -1, retIKey24($host_id));
    }
}

$res = mysqli_query($db, "SELECT * FROM `reminders` WHERE `endtime` < '".time()."' AND `noticed` = '0'");
$rows = mysqli_num_rows($res);
if($rows > 0) {
    while($row = mysqli_fetch_assoc($res)) {
        $id = $row['id'];
        $details = $row['details'];
        $user = $row['addby'];
        sendMessage($user, "Reminder#<code>$id</code>:\n$details");
        sendQuery("UPDATE `reminders` SET `noticed` = '1' WHERE `id` = '$id'");
    }
}

$res = mysqli_query($db, "SELECT * FROM `users` WHERE `step` LIKE '%getcode_%'");
$rows = mysqli_num_rows($res);
if($rows > 0) {
    while($row = mysqli_fetch_assoc($res)) {
        $step = $row['step'];
        $codeid = str_replace('getcode_', '', $step);
        $price = explode(':', $codeid)[1];
        $codeid = explode(':', $codeid)[0];
        $user = $row['id'];
        $data = json_decode(checkNum($codeid), true);
        if($data['RESULT'] == '1' || $data['RESULT'] == '5') {
            sendMessage($user, "<b>*</b> WAITING FOR CODE...");
        }
        elseif($data['RESULT'] == '2') {
            $code = $data['CODE'];
            sendMessage($user, "<b>*</b> Your code is: <code>$code</code>");
            $code ++;
        }
        elseif($data['RESULT'] == '3') {
            setUser($user, 'step', '-1');
            setUser($user, 'balance', (getUser($user, 'balance') + $price));
            sendMessage($user, "<b>*</b> NUMBER GOT CANCELLED\n<code>$price Stock Coins</code> refunded to your account wallet");
        }
        elseif($data['RESULT'] == '4') {
            setUser($user, 'step', '-1');
            setUser($user, 'balance', (getUser($user, 'balance') + $price));
            sendMessage($user, "<b>*</b> NUMBER GOT BANNED\n<code>$price Stock Coins</code> refunded to your account wallet");
        }
        elseif($data['RESULT'] == '6') {
            setUser($user, 'step', '-1');
            sendMessage($user, "<b>*</b> Process completed");
        }
    }
}

if(date('H') >= '00' && date('H') <= '01') {
    if(date('H') == '00' && date('i') == '00') {
        $backup = createBackup();
        $fileName = $backup['fileName'];
        $sqlName = $backup['sqlName'];
        $files = $backup['files'];
        $size = $backup['size'];
        $document = $backup['link'];
        $res = mysqli_query($db, "SELECT * FROM `users` WHERE `admin` > '1'");
        $rows = mysqli_num_rows($res);
        if($rows > 0) {
            while($row = mysqli_fetch_assoc($res)) {
                sendDocument($row['id'], $document, "<code>AUTOMATICALLY 24 HOURS BACKUP</code>\n\nFiles: <code>$files</code>\nSize: <code>$size</code>\n\n#backup\n[ <code>".date('Y-m-d')."</code> ]");
            }
            $backup = true;
        }
        unlink($fileName);
        unlink($sqlName);
    }
}

$res = mysqli_query($db, "SELECT * FROM `users` WHERE `dbid` >= '$cron' AND `dbid` < '$nextcron'");
$rows = mysqli_num_rows($res);
if($rows > 0) {
    $shuser = -1;
    while($row = mysqli_fetch_assoc($res)) {
        if($row['id'] == $bot_id) {
            continue;
        }
        if(isSubExpired($row['id']) && !isUserAdmin($row['id'])) {
            array_push($users, $row['id']);
        }
        if(!isSubExpired($row['id'])) {
            $sub = getUser($row['id'], 'subscription');
            $alarm = getUser($row['id'], 'alarm');
            $day = 3;
            if(($sub) < (time() + DAYS($day))) {
                if($alarm == '0') {
                    sendMessage($row['id'], "Less than <b>$day</b> days left to your group subscription expire");
                    setUser($row['id'], 'alarm', $day);
                }
            }
        }
    }
}

$res = mysqli_query($db, "SELECT * FROM `chats` WHERE `vip` > '0'");
$rows = mysqli_num_rows($res);
if($rows > 0) {
    while($row = mysqli_fetch_assoc($res)) {
        array_push($chats, $row['chat_id']);
    }
}

foreach($chats as $chat) {
    foreach($users as $id) {
        $get = getChatMember($chat, $id);
        if(!isUserAdmin($id) && $get == 'member') {
            $mention = mentionUser($id);
            $name = bot('getChat', array('chat_id' => $chat))->result->title;
            banChatMember($chat, $id);
            sendMessage($chat, "<b>*</b> User $mention's group subscription expired. (<b>Kicked</b>)");
            sendMessage($id, "<code>*</code> You have kicked from <b>$name</b> group because of your subscription expire time");
            setUser($id, 'alarm', '0');
            setUser($id, 'double', '-1');
            $rcount ++;
        }
    }
}

foreach($users as $id) {
    $shalarm = 0;
    $shid = -1;
    $res = mysqli_query($db, "SELECT * FROM `sharedbuy` WHERE `user` = '$id'");
    $rows = mysqli_num_rows($res);
    if($rows > 0) {
        $dbid = -1;
        while($row = mysqli_fetch_assoc($res)) {
            $dbid = $row['dbid'];
            $shid = $row['id'];
            $shalarm = $row['alarm'];
        }
        $res = mysqli_query($db, "SELECT * FROM `sharedaccounts` WHERE `id` = '$dbid'");
        $rows = mysqli_num_rows($res);
        if($rows > 0) {
            while($row = mysqli_fetch_assoc($res)) {
                $dbid = $row['dbid'];
            }
            $res = mysqli_query($db, "SELECT * FROM `shared` WHERE `id` = '$dbid'");
            $rows = mysqli_num_rows($res);
            if($rows > 0) {
                $name = "null";
                while($row = mysqli_fetch_assoc($res)) {
                    $name = $row['name'];
                }
                if(isSharedExpired($id, $name) && $shalarm == '0') {
                    $mention = mentionUser($id);
                    sendQuery("UPDATE `sharedbuy` SET `alarm` = '1' WHERE `id` = '$shid' AND `user` = '$id'");
                    sendMessage($id, "Your subscription to <code>$name</code> shared account has expired");
                    sendAdminMessage("#admin\nUser $mention's subscription to <code>$name</code> shared account has expired");
                }
            }
        }
    }
}

setSettings('cron', $nextcron);
$cend = microtime(true);

echo json_encode(array('status' => true, 'result' => array('cronjob checked' => $cron, 'backup sent' => $backup, 'alarms sent' => $acount, 'removed users' => $rcount, 'codes received' => $code, 'messages to all' => $message, 'execution time' => round($cend - $cstart))), 128).PHP_EOL;